Setup project
toliboff/Leaderboard pull request #1
Opened 2021-07-26 15:21 UTC by toliboff

## Project requirements
*IMPORTANT NOTE*:  This is the first time you will use Gitflow. 
- Create an npm project with webpack.
- Write plain HTML markup with minimum styling (just to make the layout), because you will implement styles in the following steps.
- Don't make API calls (you'll do it in the following lesson).
- Use ES6 modules, with import and export.

2021-07-26 16:29 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-26 16:29 UTC, vichuge commented on package.json
> +  },
- [ ] Please, add the next function on the script. `"dev": "webpack --mode development",`

2021-07-26 16:29 UTC, vichuge commented on src/index.html
> +  </main>
- [ ] It looks like you add everything directly on the `index.html` file. In this case, try to use index.html main contain an only root element (in this case you use `<script src="main.js"></script>`). After you called root, try to add all this on the HTML file using js. Remember to follow all ES6 best practices.

2021-07-27 03:28 UTC, carlos-ssh approved these changes
Hi @toliboff, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-27 03:28 UTC, carlos-ssh commented on README.md
> +
[OPTIONAL]
- Provide a License.

2021-07-27 05:11 UTC, merged